spring:
  datasource:
    url: jdbc:mysql://jiguhada.cow5csvaolbm.ap-northeast-2.rds.amazonaws.com:3306/jiguhada
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jiguhada
    password: wlrn2022!
    hikari:
      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false

